name: trivia_tdd
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  equatable: ^2.0.3
  flutter_bloc: ^8.0.0
  get_cli: ^1.7.1
  get_it: ^7.2.0
  http: ^0.13.4
  shared_preferences: ^2.0.11
  data_connection_checker: 0.3.4
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  mockito: ^5.0.17
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

